name: Release

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          cd pkg
          for p in */; do
            cd "$p"
            zip -r "${p%/}.zip" "${p%/}" -x "*.DS_Store" && mv "${p%/}.zip" ../
            cd ..
          done
          cd ..

      - name: Upload style to release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: pkg/*.zip